using Microsoft.EntityFrameworkCore;
using Wpm.Domain;

namespace Wpm.Dal;

public class WpmDbContext(DbContextOptions<WpmDbContext> options) : DbContext(options)
{
    public DbSet<Species> Species { get; set; }
    public DbSet<Pet> Pets { get; set; }
    public DbSet<Breed> Breeds { get; set; }
    public DbSet<Owner> Owners { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Owner>().HasData(
                    new Owner() { Id = 1, Name = "Rodrigo" },
                    new Owner() { Id = 2, Name = "Leonardo" },
                    new Owner() { Id = 3, Name = "Alicia" },
                    new Owner() { Id = 4, Name = "Jon" },
                    new Owner() { Id = 5, Name = "Elmer" },
                    new Owner() { Id = 6, Name = "Sam" },
                    new Owner() { Id = 7, Name = "Jessica" },
                    new Owner() { Id = 8, Name = "Alex Brown" },
                    new Owner() { Id = 9, Name = "Cameron Brown" },
                    new Owner() { Id = 10, Name = "Jamie Miller" },
                    new Owner() { Id = 11, Name = "Charlie Brown" },
                    new Owner() { Id = 12, Name = "Casey Garcia" },
                    new Owner() { Id = 13, Name = "Skyler Rodriguez" },
                    new Owner() { Id = 14, Name = "Charlie Miller" },
                    new Owner() { Id = 15, Name = "Sam Miller" },
                    new Owner() { Id = 16, Name = "Jamie Jones" },
                    new Owner() { Id = 17, Name = "Skyler Johnson" },
                    new Owner() { Id = 18, Name = "Morgan Davis" },
                    new Owner() { Id = 19, Name = "Charlie Johnson" },
                    new Owner() { Id = 20, Name = "Jamie Smith" },
                    new Owner() { Id = 21, Name = "Jordan Williams" },
                    new Owner() { Id = 22, Name = "Charlie Jones" },
                    new Owner() { Id = 23, Name = "Jamie Garcia" },
                    new Owner() { Id = 24, Name = "Casey Jones" },
                    new Owner() { Id = 25, Name = "Skyler Jones" },
                    new Owner() { Id = 26, Name = "Skyler Rodriguez" },
                    new Owner() { Id = 27, Name = "Alex Brown" },
                    new Owner() { Id = 28, Name = "Skyler Davis" },
                    new Owner() { Id = 29, Name = "Casey Johnson" },
                    new Owner() { Id = 30, Name = "Morgan Miller" },
                    new Owner() { Id = 31, Name = "Jamie Wilson" },
                    new Owner() { Id = 32, Name = "Casey Brown" },
                    new Owner() { Id = 33, Name = "Alex Johnson" },
                    new Owner() { Id = 34, Name = "Jamie Smith" },
                    new Owner() { Id = 35, Name = "Alex Rodriguez" },
                    new Owner() { Id = 36, Name = "Taylor Davis" },
                    new Owner() { Id = 37, Name = "Charlie Johnson" },
                    new Owner() { Id = 38, Name = "Casey Garcia" },
                    new Owner() { Id = 39, Name = "Morgan Rodriguez" },
                    new Owner() { Id = 40, Name = "Morgan Wilson" },
                    new Owner() { Id = 41, Name = "Morgan Garcia" },
                    new Owner() { Id = 42, Name = "Sam Jones" },
                    new Owner() { Id = 43, Name = "Morgan Williams" },
                    new Owner() { Id = 44, Name = "Casey Smith" },
                    new Owner() { Id = 45, Name = "Casey Wilson" },
                    new Owner() { Id = 46, Name = "Alex Garcia" },
                    new Owner() { Id = 47, Name = "Morgan Garcia" },
                    new Owner() { Id = 48, Name = "Jamie Garcia" },
                    new Owner() { Id = 49, Name = "Alex Rodriguez" },
                    new Owner() { Id = 50, Name = "Sam Wilson" },
                    new Owner() { Id = 51, Name = "Sam Miller" },
                    new Owner() { Id = 52, Name = "Cameron Williams" },
                    new Owner() { Id = 53, Name = "Jordan Miller" },
                    new Owner() { Id = 54, Name = "Sam Garcia" },
                    new Owner() { Id = 55, Name = "Morgan Rodriguez" },
                    new Owner() { Id = 56, Name = "Charlie Rodriguez" },
                    new Owner() { Id = 57, Name = "Charlie Jones" }
                    );
        modelBuilder.Entity<Species>().HasData(
                    new Species() { Id = 1, Name = "Dog" },
                    new Species() { Id = 2, Name = "Cat" },
                    new Species() { Id = 3, Name = "Rabbit" }
                    );
        modelBuilder.Entity<Breed>().HasData(
                    new Breed() { Id = 1, Name = "Beagle", IdealMaxWeight = 20, SpeciesId = 1 },
                    new Breed() { Id = 2, Name = "Staffordshire Terrier", IdealMaxWeight = 25, SpeciesId = 1 },
                    new Breed() { Id = 3, Name = "British Shorthair", IdealMaxWeight = 20, SpeciesId = 2 },
                    new Breed() { Id = 4, Name = "Mixed", IdealMaxWeight = 30, SpeciesId = 2 },
                    new Breed() { Id = 5, Name = "Gray", IdealMaxWeight = 20, SpeciesId = 3 },
                    new Breed() { Id = 6, Name = "American White", IdealMaxWeight = 30, SpeciesId = 3 },
                    new Breed() { Id = 7, Name = "Labrador Retriever", IdealMaxWeight = 20, SpeciesId = 1 },
                    new Breed() { Id = 8, Name = "German Shepherd", IdealMaxWeight = 20, SpeciesId = 1 },
                    new Breed() { Id = 9, Name = "Golden Retriever", IdealMaxWeight = 20, SpeciesId = 1 },
                    new Breed() { Id = 10, Name = "Bulldog", IdealMaxWeight = 20, SpeciesId = 1 },
                    new Breed() { Id = 11, Name = "Cocker Spaniel", IdealMaxWeight = 20, SpeciesId = 1 },
                    new Breed() { Id = 12, Name = "Persian", IdealMaxWeight = 15, SpeciesId = 2 },
                    new Breed() { Id = 13, Name = "Maine Coon", IdealMaxWeight = 15, SpeciesId = 2 },
                    new Breed() { Id = 14, Name = "Ragdoll", IdealMaxWeight = 15, SpeciesId = 2 },
                    new Breed() { Id = 15, Name = "Siamese", IdealMaxWeight = 15, SpeciesId = 2 },
                    new Breed() { Id = 16, Name = "Bengal", IdealMaxWeight = 15, SpeciesId = 2 },
                    new Breed() { Id = 17, Name = "Holland Lop", IdealMaxWeight = 5, SpeciesId = 3 },
                    new Breed() { Id = 18, Name = "Netherland Dwarf", IdealMaxWeight = 5, SpeciesId = 3 },
                    new Breed() { Id = 19, Name = "Rex", IdealMaxWeight = 5, SpeciesId = 3 },
                    new Breed() { Id = 20, Name = "Mini Lop", IdealMaxWeight = 5, SpeciesId = 3 },
                    new Breed() { Id = 21, Name = "Lionhead", IdealMaxWeight = 5, SpeciesId = 3 }
                    );
        modelBuilder.Entity<Pet>().HasData(
                    new Pet() { Id = 1, Name = "Gianni", Age = 10, Weight = 19, PhotoUrl = "/images/gianni.jpg", BreedId = 1 },
                    new Pet() { Id = 2, Name = "Nina", Age = 8, Weight = 24, PhotoUrl = "/images/nina.jpg", BreedId = 1 },
                    new Pet() { Id = 3, Name = "Cati", Age = 8, Weight = 33.5m, PhotoUrl = "/images/cati.jpg", BreedId = 2 },
                    new Pet() { Id = 4, Name = "Cheshire", Age = 20, Weight = 12, BreedId = 3 },
                    new Pet() { Id = 5, Name = "Garfield", Age = 20, Weight = 12, BreedId = 4 },
                    new Pet() { Id = 6, Name = "Bugs", Age = 40, Weight = 25, BreedId = 5 },
                    new Pet() { Id = 7, Name = "Roger", Age = 35, Weight = 31, BreedId = 6 },
                    new Pet() { Id = 8, Name = "Snowball", Age = 3, Weight = 25, BreedId = 13 },
                    new Pet() { Id = 9, Name = "Rocky", Age = 9, Weight = 24, BreedId = 13 },
                    new Pet() { Id = 10, Name = "Nala", Age = 5, Weight = 5, BreedId = 14 },
                    new Pet() { Id = 11, Name = "Cotton", Age = 15, Weight = 5, BreedId = 17 },
                    new Pet() { Id = 12, Name = "Lucy", Age = 5, Weight = 22, BreedId = 14 },
                    new Pet() { Id = 13, Name = "Charlie", Age = 8, Weight = 10, BreedId = 15 },
                    new Pet() { Id = 14, Name = "Peanut", Age = 14, Weight = 7, BreedId = 12 },
                    new Pet() { Id = 15, Name = "Charlie", Age = 13, Weight = 7, BreedId = 21 },
                    new Pet() { Id = 16, Name = "Leo", Age = 7, Weight = 27, BreedId = 9 },
                    new Pet() { Id = 17, Name = "Flopsy", Age = 10, Weight = 28, BreedId = 18 },
                    new Pet() { Id = 18, Name = "Coco", Age = 2, Weight = 25, BreedId = 3 },
                    new Pet() { Id = 19, Name = "Simba", Age = 5, Weight = 26, BreedId = 14 },
                    new Pet() { Id = 20, Name = "Cotton", Age = 14, Weight = 27, BreedId = 10 },
                    new Pet() { Id = 21, Name = "Daisy", Age = 3, Weight = 30, BreedId = 3 },
                    new Pet() { Id = 22, Name = "Jack", Age = 10, Weight = 30, BreedId = 14 },
                    new Pet() { Id = 23, Name = "Thumper", Age = 7, Weight = 19, BreedId = 9 },
                    new Pet() { Id = 24, Name = "Lucy", Age = 7, Weight = 5, BreedId = 1 },
                    new Pet() { Id = 25, Name = "Jack", Age = 10, Weight = 23, BreedId = 8 },
                    new Pet() { Id = 26, Name = "Cotton", Age = 11, Weight = 20, BreedId = 11 },
                    new Pet() { Id = 27, Name = "Coco", Age = 14, Weight = 29, BreedId = 5 },
                    new Pet() { Id = 28, Name = "Oliver", Age = 9, Weight = 13, BreedId = 15 },
                    new Pet() { Id = 29, Name = "Cotton", Age = 14, Weight = 12, BreedId = 21 },
                    new Pet() { Id = 30, Name = "Daisy", Age = 4, Weight = 23, BreedId = 12 },
                    new Pet() { Id = 31, Name = "Luna", Age = 10, Weight = 24, BreedId = 2 },
                    new Pet() { Id = 32, Name = "Mopsy", Age = 6, Weight = 20, BreedId = 6 },
                    new Pet() { Id = 33, Name = "Lucy", Age = 7, Weight = 30, BreedId = 19 },
                    new Pet() { Id = 34, Name = "Nala", Age = 6, Weight = 14, BreedId = 12 },
                    new Pet() { Id = 35, Name = "Thumper", Age = 9, Weight = 27, BreedId = 20 },
                    new Pet() { Id = 36, Name = "Lucy", Age = 1, Weight = 20, BreedId = 15 },
                    new Pet() { Id = 37, Name = "Leo", Age = 1, Weight = 21, BreedId = 18 },
                    new Pet() { Id = 38, Name = "Oreo", Age = 1, Weight = 5, BreedId = 4 },
                    new Pet() { Id = 39, Name = "Bailey", Age = 15, Weight = 22, BreedId = 11 },
                    new Pet() { Id = 40, Name = "Simba", Age = 15, Weight = 29, BreedId = 16 },
                    new Pet() { Id = 41, Name = "Thumper", Age = 1, Weight = 7, BreedId = 20 },
                    new Pet() { Id = 42, Name = "Bailey", Age = 7, Weight = 29, BreedId = 11 },
                    new Pet() { Id = 43, Name = "Jack", Age = 3, Weight = 5, BreedId = 3 },
                    new Pet() { Id = 44, Name = "BunBun", Age = 3, Weight = 20, BreedId = 12 },
                    new Pet() { Id = 45, Name = "Bella", Age = 11, Weight = 6, BreedId = 21 },
                    new Pet() { Id = 46, Name = "Bella", Age = 13, Weight = 7, BreedId = 2 },
                    new Pet() { Id = 47, Name = "Oreo", Age = 13, Weight = 18, BreedId = 2 },
                    new Pet() { Id = 48, Name = "Bella", Age = 3, Weight = 7, BreedId = 12 },
                    new Pet() { Id = 49, Name = "Charlie", Age = 7, Weight = 21, BreedId = 16 },
                    new Pet() { Id = 50, Name = "Snowball", Age = 13, Weight = 13, BreedId = 13 },
                    new Pet() { Id = 51, Name = "Rocky", Age = 6, Weight = 17, BreedId = 17 },
                    new Pet() { Id = 52, Name = "Bella", Age = 10, Weight = 26, BreedId = 8 },
                    new Pet() { Id = 53, Name = "Cotton", Age = 2, Weight = 30, BreedId = 8 },
                    new Pet() { Id = 54, Name = "Buddy", Age = 11, Weight = 22, BreedId = 20 },
                    new Pet() { Id = 55, Name = "Bella", Age = 4, Weight = 5, BreedId = 11 },
                    new Pet() { Id = 56, Name = "Peanut", Age = 15, Weight = 24, BreedId = 10 },
                    new Pet() { Id = 57, Name = "Bailey", Age = 14, Weight = 10, BreedId = 18 },
                    new Pet() { Id = 58, Name = "Max", Age = 9, Weight = 8, BreedId = 1 },
                    new Pet() { Id = 59, Name = "Peanut", Age = 7, Weight = 15, BreedId = 14 },
                    new Pet() { Id = 60, Name = "Charlie", Age = 2, Weight = 14, BreedId = 1 },
                    new Pet() { Id = 61, Name = "Jack", Age = 4, Weight = 14, BreedId = 5 },
                    new Pet() { Id = 62, Name = "BunBun", Age = 1, Weight = 8, BreedId = 7 },
                    new Pet() { Id = 63, Name = "Rocky", Age = 2, Weight = 22, BreedId = 9 },
                    new Pet() { Id = 64, Name = "Jack", Age = 11, Weight = 8, BreedId = 1 },
                    new Pet() { Id = 65, Name = "Peanut", Age = 6, Weight = 26, BreedId = 6 },
                    new Pet() { Id = 66, Name = "Bailey", Age = 14, Weight = 29, BreedId = 16 },
                    new Pet() { Id = 67, Name = "Nala", Age = 14, Weight = 28, BreedId = 16 },
                    new Pet() { Id = 68, Name = "Cinnabun", Age = 13, Weight = 27, BreedId = 10 },
                    new Pet() { Id = 69, Name = "Molly", Age = 11, Weight = 26, BreedId = 9 },
                    new Pet() { Id = 70, Name = "Bella", Age = 3, Weight = 23, BreedId = 17 },
                    new Pet() { Id = 71, Name = "Peanut", Age = 8, Weight = 23, BreedId = 5 },
                    new Pet() { Id = 72, Name = "Bella", Age = 5, Weight = 26, BreedId = 11 },
                    new Pet() { Id = 73, Name = "Charlie", Age = 11, Weight = 16, BreedId = 19 },
                    new Pet() { Id = 74, Name = "BunBun", Age = 8, Weight = 8, BreedId = 13 },
                    new Pet() { Id = 75, Name = "Molly", Age = 5, Weight = 15, BreedId = 7 },
                    new Pet() { Id = 76, Name = "Leo", Age = 5, Weight = 16, BreedId = 9 },
                    new Pet() { Id = 77, Name = "Flopsy", Age = 15, Weight = 14, BreedId = 4 },
                    new Pet() { Id = 78, Name = "Max", Age = 9, Weight = 6, BreedId = 2 },
                    new Pet() { Id = 79, Name = "Milo", Age = 8, Weight = 12, BreedId = 18 },
                    new Pet() { Id = 80, Name = "Thumper", Age = 10, Weight = 17, BreedId = 8 },
                    new Pet() { Id = 81, Name = "Molly", Age = 3, Weight = 6, BreedId = 16 },
                    new Pet() { Id = 82, Name = "Luna", Age = 5, Weight = 23, BreedId = 10 },
                    new Pet() { Id = 83, Name = "BunBun", Age = 3, Weight = 24, BreedId = 19 },
                    new Pet() { Id = 84, Name = "Max", Age = 6, Weight = 8, BreedId = 7 },
                    new Pet() { Id = 85, Name = "Max", Age = 10, Weight = 26, BreedId = 5 },
                    new Pet() { Id = 86, Name = "Cotton", Age = 1, Weight = 15, BreedId = 21 },
                    new Pet() { Id = 87, Name = "Bella", Age = 7, Weight = 23, BreedId = 14 },
                    new Pet() { Id = 88, Name = "Nala", Age = 1, Weight = 10, BreedId = 14 },
                    new Pet() { Id = 89, Name = "BunBun", Age = 3, Weight = 25, BreedId = 8 },
                    new Pet() { Id = 90, Name = "Coco", Age = 12, Weight = 18, BreedId = 4 },
                    new Pet() { Id = 91, Name = "Oliver", Age = 8, Weight = 8, BreedId = 4 },
                    new Pet() { Id = 92, Name = "Mopsy", Age = 7, Weight = 8, BreedId = 5 },
                    new Pet() { Id = 93, Name = "Buddy", Age = 10, Weight = 18, BreedId = 17 },
                    new Pet() { Id = 94, Name = "Max", Age = 2, Weight = 27, BreedId = 14 },
                    new Pet() { Id = 95, Name = "Flopsy", Age = 10, Weight = 28, BreedId = 16 },
                    new Pet() { Id = 96, Name = "Lucy", Age = 6, Weight = 5, BreedId = 15 },
                    new Pet() { Id = 97, Name = "Simba", Age = 15, Weight = 24, BreedId = 21 },
                    new Pet() { Id = 98, Name = "Daisy", Age = 11, Weight = 11, BreedId = 11 },
                    new Pet() { Id = 99, Name = "Charlie", Age = 13, Weight = 8, BreedId = 8 },
                    new Pet() { Id = 100, Name = "Charlie", Age = 13, Weight = 19, BreedId = 12 },
                    new Pet() { Id = 101, Name = "Flopsy", Age = 2, Weight = 5, BreedId = 5 },
                    new Pet() { Id = 102, Name = "Max", Age = 4, Weight = 20, BreedId = 15 },
                    new Pet() { Id = 103, Name = "Max", Age = 8, Weight = 27, BreedId = 4 },
                    new Pet() { Id = 104, Name = "Thumper", Age = 1, Weight = 19, BreedId = 9 },
                    new Pet() { Id = 105, Name = "Lucy", Age = 14, Weight = 28, BreedId = 2 },
                    new Pet() { Id = 106, Name = "Luna", Age = 6, Weight = 27, BreedId = 13 },
                    new Pet() { Id = 107, Name = "Daisy", Age = 2, Weight = 26, BreedId = 11 }
                    );
        modelBuilder.Entity("OwnerPet").HasData(
                    [
                        new { PetsId = 1, OwnersId = 1 },
                        new { PetsId = 1, OwnersId = 2 },
                        new { PetsId = 2, OwnersId = 1 },
                        new { PetsId = 2, OwnersId = 2 },
                        new { PetsId = 3, OwnersId = 1 },
                        new { PetsId = 3, OwnersId = 2 },
                        new { PetsId = 4, OwnersId = 3 },
                        new { PetsId = 5, OwnersId = 4 },
                        new { PetsId = 6, OwnersId = 5 },
                        new { PetsId = 6, OwnersId = 6 },
                        new { PetsId = 7, OwnersId = 7 },
                        new { PetsId = 48, OwnersId = 29 },
                        new { PetsId = 62, OwnersId = 32 },
                        new { PetsId = 16, OwnersId = 56 },
                        new { PetsId = 94, OwnersId = 11 },
                        new { PetsId = 52, OwnersId = 35 },
                        new { PetsId = 33, OwnersId = 40 },
                        new { PetsId = 38, OwnersId = 11 },
                        new { PetsId = 35, OwnersId = 44 },
                        new { PetsId = 14, OwnersId = 22 },
                        new { PetsId = 63, OwnersId = 12 },
                        new { PetsId = 73, OwnersId = 53 },
                        new { PetsId = 102, OwnersId = 57 },
                        new { PetsId = 9, OwnersId = 34 },
                        new { PetsId = 27, OwnersId = 8 },
                        new { PetsId = 28, OwnersId = 11 },
                        new { PetsId = 15, OwnersId = 38 },
                        new { PetsId = 91, OwnersId = 10 },
                        new { PetsId = 100, OwnersId = 19 },
                        new { PetsId = 39, OwnersId = 19 },
                        new { PetsId = 19, OwnersId = 48 },
                        new { PetsId = 21, OwnersId = 55 },
                        new { PetsId = 30, OwnersId = 9 },
                        new { PetsId = 31, OwnersId = 43 },
                        new { PetsId = 91, OwnersId = 25 },
                        new { PetsId = 38, OwnersId = 53 },
                        new { PetsId = 17, OwnersId = 13 },
                        new { PetsId = 86, OwnersId = 8 },
                        new { PetsId = 79, OwnersId = 25 },
                        new { PetsId = 93, OwnersId = 13 },
                        new { PetsId = 50, OwnersId = 10 },
                        new { PetsId = 33, OwnersId = 16 },
                        new { PetsId = 98, OwnersId = 55 },
                        new { PetsId = 28, OwnersId = 18 },
                        new { PetsId = 40, OwnersId = 52 },
                        new { PetsId = 91, OwnersId = 27 },
                        new { PetsId = 45, OwnersId = 39 },
                        new { PetsId = 60, OwnersId = 25 },
                        new { PetsId = 71, OwnersId = 9 },
                        new { PetsId = 105, OwnersId = 36 },
                        new { PetsId = 50, OwnersId = 22 },
                        new { PetsId = 12, OwnersId = 52 },
                        new { PetsId = 19, OwnersId = 35 },
                        new { PetsId = 85, OwnersId = 37 },
                        new { PetsId = 27, OwnersId = 14 },
                        new { PetsId = 63, OwnersId = 22 },
                        new { PetsId = 41, OwnersId = 33 },
                        new { PetsId = 67, OwnersId = 44 },
                        new { PetsId = 91, OwnersId = 9 },
                        new { PetsId = 20, OwnersId = 23 },
                        new { PetsId = 37, OwnersId = 11 },
                        new { PetsId = 74, OwnersId = 25 },
                        new { PetsId = 78, OwnersId = 50 },
                        new { PetsId = 50, OwnersId = 57 },
                        new { PetsId = 70, OwnersId = 33 },
                        new { PetsId = 18, OwnersId = 18 },
                        new { PetsId = 97, OwnersId = 50 },
                        new { PetsId = 54, OwnersId = 30 },
                        new { PetsId = 14, OwnersId = 24 },
                        new { PetsId = 30, OwnersId = 21 },
                        new { PetsId = 50, OwnersId = 20 },
                        new { PetsId = 34, OwnersId = 39 },
                        new { PetsId = 48, OwnersId = 13 },
                        new { PetsId = 78, OwnersId = 42 },
                        new { PetsId = 37, OwnersId = 13 },
                        new { PetsId = 92, OwnersId = 11 },
                        new { PetsId = 84, OwnersId = 41 },
                        new { PetsId = 58, OwnersId = 29 },
                        new { PetsId = 90, OwnersId = 28 },
                        new { PetsId = 36, OwnersId = 46 },
                        new { PetsId = 36, OwnersId = 53 },
                        new { PetsId = 49, OwnersId = 43 },
                        new { PetsId = 107, OwnersId = 20 },
                        new { PetsId = 56, OwnersId = 53 },
                        new { PetsId = 35, OwnersId = 53 },
                        new { PetsId = 103, OwnersId = 39 },
                        new { PetsId = 65, OwnersId = 47 },
                        new { PetsId = 45, OwnersId = 47 },
                        new { PetsId = 81, OwnersId = 16 },
                        new { PetsId = 9, OwnersId = 49 },
                        new { PetsId = 60, OwnersId = 32 },
                        new { PetsId = 53, OwnersId = 52 },
                        new { PetsId = 43, OwnersId = 52 },
                        new { PetsId = 60, OwnersId = 47 },
                        new { PetsId = 93, OwnersId = 21 },
                        new { PetsId = 34, OwnersId = 25 },
                        new { PetsId = 10, OwnersId = 15 },
                        new { PetsId = 45, OwnersId = 43 },
                        new { PetsId = 62, OwnersId = 34 },
                        new { PetsId = 58, OwnersId = 23 },
                        new { PetsId = 10, OwnersId = 22 },
                        new { PetsId = 47, OwnersId = 54 },
                        new { PetsId = 37, OwnersId = 21 },
                        new { PetsId = 77, OwnersId = 47 },
                        new { PetsId = 62, OwnersId = 9 },
                        new { PetsId = 15, OwnersId = 29 },
                        new { PetsId = 99, OwnersId = 10 },
                        new { PetsId = 71, OwnersId = 43 },
                        new { PetsId = 75, OwnersId = 32 },
                        new { PetsId = 57, OwnersId = 25 },
                        new { PetsId = 57, OwnersId = 10 },
                        new { PetsId = 51, OwnersId = 52 },
                        new { PetsId = 60, OwnersId = 10 },
                        new { PetsId = 89, OwnersId = 14 },
                        new { PetsId = 42, OwnersId = 52 },
                        new { PetsId = 58, OwnersId = 35 },
                        new { PetsId = 22, OwnersId = 31 },
                        new { PetsId = 94, OwnersId = 24 },
                        new { PetsId = 12, OwnersId = 18 },
                        new { PetsId = 9, OwnersId = 20 },
                        new { PetsId = 97, OwnersId = 43 }
                    ]
                );
    }
}